//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace practiceproject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_customer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_customer()
        {
            this.tbl_order = new HashSet<tbl_order>();
        }
    
        public int ID { get; set; }
        public Nullable<System.DateTime> DATE { get; set; }
        public string CUSTOMER_NAME { get; set; }
        public Nullable<System.DateTime> DELIVERY_DATE { get; set; }
        public string BROKER { get; set; }
        public string TOTAL { get; set; }
        public string FILE_UPLOAD { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_order> tbl_order { get; set; }
    }
}
